#! /bin/sh
LD_LIBRARY_PATH=$(pwd)/ipasir-cryptominisat/lib/linux/
echo $LD_LIBRARY_PATH
rm -rf .stack-work/
rm -rf ipasir/.stack-work/
rm -rf ipasir-cryptominisat/.stack-work/
stack install --test --extra-lib-dirs=$LD_LIBRARY_PATH
cat .stack-work/logs/ipasir-cryptominisat-0.1.0.0-test.log